version: "3"
services:
  db:
    image: postgres
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgress
     - POSTGRES_DB=postgres
    ports:
     - "5432:5432"
    volumes:
     - pgdata:/var/lib/postgresql/data
       
  app:
    build: .
    environment:
      - DB_NAME=social_connect
      - DB_USER=django
      - DB_PASSWORD=fky#we6hbj@5tfg23^gfw2g!j
      - DB_HOST=db
      - DB_PORT=5432
      - LOGSTASH_HOST=localhost
      - LOGSTASH_PORT=5959
      - SECRET_KEY=-oolx&#0ty125q%(q6dy5@!7jj+o7+x14c0&+-2dn2tthlz30
      - DEBUG=-oolx&#0ty125q%(q6dy5@!7jj+o7+x14c0&+-2dn2tthlz30
      - FLUENT_HOST=fluent
    ports:
      - "8000:8000"
    depends_on:
      - db
      - fluent

  elasticsearch:
    labels:
      com.example.service: "elasticsearch"
      com.example.description: "For searching and indexing data"
    image: elasticsearch:6.8.14
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  fluent:
    labels:
      com.example.service: "fluentd"
      com.example.description: "For logging data"
    build:
      context: fluent
    volumes:
      - "./fluent/fluent.conf:/fluentd/etc/fluent.conf"
    depends_on:
      - elasticsearch
    ports:
      - "24224:24224"
      - "24224:24224/udp"

#
#  kibana:
#    labels:
#      com.example.service: "kibana"
#      com.example.description: "Data visualisation and for log aggregation"
#    image: kibana:7.11.2
#    ports:
#      - "5601:5601"
#    environment:
#      - ELASTICSEARCH_URL=http://elasticsearch:9200
#    depends_on:
#      - elasticsearch

volumes:
  pgdata:
  esdata:
