apiVersion: v1
kind: Service
metadata:
  name: social-connect
  labels:
    app: social-connect
spec:
  type: NodePort
  selector:
    app: social-connect
  ports:
    - port: 8000
      targetPort: 8000
