source "https://rubygems.org"

gem "fluentd", "1.12.0"
gem "oj", "3.11.0"
gem "fluent-plugin-multi-format-parser", "~> 1.0.0"
gem 'fluent-plugin-json-in-json-2', ">= 1.0.2"
gem "fluent-plugin-record-modifier", "~> 2.1.0"
gem "fluent-plugin-rewrite-tag-filter", "~> 2.4.0"
gem "fluent-plugin-elasticsearch", "~> 5.0.2"
